listen_addresses = '*'

# 물리 복제 활성화
wal_level = replica
max_wal_senders = 10
wal_keep_size = 64MB

# 복제 슬롯 최대 개수
max_replication_slots = 10

# WAL 아카이브 설정
archive_mode = on
archive_command = 'cp %p /wal_archive/%f'

# standby 노드의 read-only 조회 허용
hot_standby = on
